version: 2
updates:
  # Enable version updates for go
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
